### ISSUE TITLE
Debian 8: failed to open file rocket-depot.svg

### ISSUE THREAD

**Issue by scottlinux** [robled/rocket-depot#82]
Installed via: sudo pip install rocket-depot

App complains of missing svg:

<pre>
stmiller@brahms:~$ rocket-depot 
Traceback (most recent call last):
  File "/usr/local/bin/rocket-depot", line 779, in <module>
    _main()
  File "/usr/local/bin/rocket-depot", line 771, in _main
    rocket_depot = RocketDepot()
  File "/usr/local/bin/rocket-depot", line 52, in __init__
    self.mw = MainWindow(self)
  File "/usr/local/bin/rocket-depot", line 258, in __init__
    self.program_icon = GdkPixbuf.Pixbuf.new_from_file("/usr/share/icons/hicolor/scalable/apps/rocket-depot.svg")
GLib.Error: g-file-error-quark: Failed to open file '/usr/share/icons/hicolor/scalable/apps/rocket-depot.svg': No such file or directory (4)
</pre>

<pre>
stmiller@brahms:~$ cat /etc/debian_version 
8.3
</pre>

**Comment by scottlinux** [comment]
This may help

<pre>
stmiller@brahms:~$ sudo pip uninstall rocket-depot
Uninstalling rocket-depot-0.25:
  /usr/local/bin/rocket-depot
  /usr/local/lib/python2.7/dist-packages/rocket_depot-0.25.dist-info/DESCRIPTION.rst
  /usr/local/lib/python2.7/dist-packages/rocket_depot-0.25.dist-info/INSTALLER
  /usr/local/lib/python2.7/dist-packages/rocket_depot-0.25.dist-info/METADATA
  /usr/local/lib/python2.7/dist-packages/rocket_depot-0.25.dist-info/RECORD
  /usr/local/lib/python2.7/dist-packages/rocket_depot-0.25.dist-info/WHEEL
  /usr/local/lib/python2.7/dist-packages/rocket_depot-0.25.dist-info/metadata.json
  /usr/local/lib/python2.7/dist-packages/rocket_depot-0.25.dist-info/top_level.txt
  /usr/local/lib/python2.7/dist-packages/usr/share/applications/rocket-depot.desktop
  /usr/local/lib/python2.7/dist-packages/usr/share/icons/hicolor/128x128/apps/rocket-depot.png
  /usr/local/lib/python2.7/dist-packages/usr/share/icons/hicolor/16x16/apps/rocket-depot.png
  /usr/local/lib/python2.7/dist-packages/usr/share/icons/hicolor/22x22/apps/rocket-depot.png
  /usr/local/lib/python2.7/dist-packages/usr/share/icons/hicolor/24x24/apps/rocket-depot.png
  /usr/local/lib/python2.7/dist-packages/usr/share/icons/hicolor/256x256/apps/rocket-depot.png
  /usr/local/lib/python2.7/dist-packages/usr/share/icons/hicolor/32x32/apps/rocket-depot.png
  /usr/local/lib/python2.7/dist-packages/usr/share/icons/hicolor/48x48/apps/rocket-depot.png
  /usr/local/lib/python2.7/dist-packages/usr/share/icons/hicolor/64x64/apps/rocket-depot.png
  /usr/local/lib/python2.7/dist-packages/usr/share/icons/hicolor/scalable/apps/rocket-depot.svg
Proceed (y/n)? y
  Successfully uninstalled rocket-depot-0.25
</pre>

**Comment by robled** [comment]
That's weird.  My setup.py is configured to put those files in **/usr/share/icons**.  I wonder if something has changed with pip that caused this.  What version of pip are you running?

**Comment by scottlinux** [comment]
<pre>
stmiller@brahms:~$ pip --version
pip 8.0.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)
</pre>

**Comment by robled** [comment]
I wouldn't be surprised if this worked with pip 7 and broke with pip 8.  I should just make a proper deb for this.

**Comment by robled** [comment]
I'm not able to reproduce this issue.  I set up a Debian 8 VM:
```
# cat /etc/debian_version 
8.3
```
It comes with a pretty old version of pip:
```
# pip -V
pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)
```
Unable to reproduce, so I brought in pip from sid:
```
# pip -V
pip 8.1.0 from /usr/lib/python2.7/dist-packages (python 2.7)
```
Still unable to reproduce.  Looks like your python environment is different from mine since you have pip 8.0.2.  I installed pip from the Debian repos and was not using a virtualenv.

**Comment by scottlinux** [comment]
Ok thanks. Feel free to close. I probably have something odd going on.

![debian](https://cloud.githubusercontent.com/assets/2176591/13799118/e9eb73ce-eaf2-11e5-97f4-5e67e219a2f1.png)

**Comment by robled** [comment]
Packages!

18e4744a8fcdff979a6ed1c9c38f5f0ce2c53560
